# Modules of essay grader

In [1]:
import os
import math
import numpy as np
import pandas as pd
import sys
import matplotlib.pyplot as plt
import pickle

from util import get_trained_model, preprocess_text

### Reading the data

In [2]:
train_data = pd.read_table("data/training_set.tsv")
rating_columns = train_data.columns.values[3:].tolist()
train_data['avg_score']=train_data[rating_columns].mean(axis=1)

## Creating a model for each grader module

In [3]:
import sklearn.feature_extraction.text as te
import sklearn.model_selection as msel
import nltk
from sklearn import preprocessing
from sklearn import metrics
from sklearn import linear_model

min_max_scaler = preprocessing.MinMaxScaler()

x = train_data.essay
y = train_data.avg_score
y_scaled = min_max_scaler.fit_transform(y.values.reshape(-1,1))

### Content module

In [4]:
get_trained_model(x, y_scaled, "content")

MODULE: content
---Transforming module data
[[0.175  0.2115 0.1415 ... 0.4175 0.288  0.237 ]]
[[0.19170984 0.23060345 0.24920128 ... 0.20361083 0.2350365  0.25878004]]
[[0.00291545 0.00236967 0.00353357 ... 0.00118343 0.0017094  0.00210526]]
---Tuning parameters
---best parameters: {'fit_intercept': False, 'normalize': True, 'copy_X': True}
---Training module on whole dataset
---Dumping module
Model dumped into: models/content_module
---------------------------------


### Grammar module

In [5]:
get_trained_model(x, y_scaled, "grammar")

MODULE: grammar
---Transforming module data
[[0.67930029 0.6943128  0.69611307 ... 0.63076923 0.69401709 0.75368421]]
---Tuning parameters
---best parameters: {'fit_intercept': False, 'normalize': True, 'copy_X': True}
---Training module on whole dataset
---Dumping module
Model dumped into: models/grammar_module
---------------------------------
